"""Statutory returns (Deklaratsioonid / Tax returns) — EE KMD/TSD surface.

Thin proxy over the engine's ``/api/v1/tax_returns`` surface (see the
engine worktree's ``saebooks/api/v1/tax_returns.py`` — Packet 4c,
commit 734b901, plus the pre-existing CRUD/list/lodge routes it extends).
The AU equivalent of this screen is the existing BAS worksheet
(``/reports/bas-summary``) + ATO SBR wizard (``/admin/ato-sbr``) — both
untouched by this packet; the sidebar surfaces this page only for a
non-AU (currently: EE) active company (see ``templates/base.html``'s
``jurisdiction`` gating, Packet 1).

GET  /tax-returns                    — list (filter by return_type/status)
POST /tax-returns/generate           — POST /api/v1/tax_returns/generate
GET  /tax-returns/{id}               — detail (figures, lodgement, actions)
GET  /tax-returns/{id}/export        — relay GET .../export (XML download)
POST /tax-returns/{id}/file          — POST .../file (manual file-and-confirm)

Known engine gap (do not fabricate a fix here — this is a proxy, the
engine repo is out of scope for this packet): there is no
``GET /api/v1/tax_periods`` (list) or create endpoint. ``TaxPeriod`` rows
are provisioned entirely outside this API surface today (payroll TSD
generation and test fixtures insert them directly). The "Generate"
action therefore cannot offer a real period picker — it takes a raw
period UUID, pre-filled from any period already visible in the list
(a `<datalist>` of period ids seen on returns already on file), so at
least the common "generate a second return type for a period we already
have a return for" case doesn't require copy-pasting from elsewhere.
Flagged, not hidden.

Return-type surface (see engine router docstring):
  * ``/generate`` only computes box-vector types (AU BAS/IAS, EE KMD) —
    422 for anything else (e.g. TSD, a list-shaped annex type).
  * ``/export`` only renders AU BAS/IAS and EE KMD — 501 for anything else
    (e.g. TSD — its own CSV/XML builders exist service-side but aren't
    wired to a generic HTTP surface, per the engine router's own
    docstring). The download button is only offered for exportable types;
    TSD returns (which land here via the payroll flow, not this screen's
    Generate button) show their figures inline instead, including any
    ``figures.errors`` data-quality warnings — surfaced, never swallowed.

Status vocabulary: the engine's ``tax_returns.status`` column is
lowercase text (``draft``/``ready``/``lodged``/``accepted``/``rejected``/
``amended``/``filed`` — see ``models/tax_return.py``'s ``TaxReturnStatus``
StrEnum), NOT the UPPERCASE convention other saebooks-web domains use
(invoices/bills/inbox). Compared against lowercase; only capitalised for
display.
"""
from __future__ import annotations

from pathlib import Path
from typing import Any
from uuid import UUID

from fastapi import APIRouter, Request
from fastapi.responses import HTMLResponse, RedirectResponse, Response
from fastapi.templating import Jinja2Templates

from saebooks_web.api_client import api_client

router = APIRouter()

_TEMPLATES_DIR = Path(__file__).resolve().parent.parent.parent / "templates"
_TEMPLATES = Jinja2Templates(directory=str(_TEMPLATES_DIR))

# Engine's real (lowercase) status vocabulary — models/tax_return.py.
_STATUSES = ("draft", "ready", "lodged", "accepted", "rejected", "amended", "filed")
# /generate only supports box-vector return types (engine router docstring).
_GENERATABLE_TYPES = ("KMD",)
# List filter offers both EE annex types the packet names; TSD returns are
# generated by the payroll flow, not this screen, but still list/view here.
_RETURN_TYPES = ("KMD", "TSD")
# /export dispatches on (jurisdiction, return_type) — anything else 501s.
_EXPORTABLE_TYPES = {("AU", "BAS"), ("AU", "IAS"), ("EE", "KMD")}


def _require_auth(request: Request) -> str | None:
    return request.session.get("api_token")


def _jurisdiction(request: Request) -> str:
    return getattr(request.state, "active_company_jurisdiction", None) or "EE"


# ---------------------------------------------------------------------------
# List
# ---------------------------------------------------------------------------


@router.get("/tax-returns", response_class=HTMLResponse, response_model=None)
async def tax_returns_list(
    request: Request,
    return_type: str | None = None,
    status: str | None = None,
) -> HTMLResponse | RedirectResponse:
    if not _require_auth(request):
        return RedirectResponse(url="/login", status_code=303)

    return_type = (return_type or "").strip().upper() or None
    status_filter = (status or "").strip().lower() or None
    if status_filter not in (None, *_STATUSES):
        status_filter = None

    params: dict[str, Any] = {}
    if return_type:
        params["return_type"] = return_type
    if status_filter:
        params["status"] = status_filter

    returns: list[dict] = []
    error: str | None = None

    async with api_client(request) as client:
        resp = await client.get("/api/v1/tax_returns", params=params)
        if resp.status_code == 401:
            request.session.clear()
            return RedirectResponse(url="/login", status_code=303)
        if resp.is_success:
            returns = resp.json().get("items", [])
        else:
            error = f"API error: HTTP {resp.status_code}"

    # Best-effort suggestions for the Generate form's period field — every
    # distinct period_id already seen on a return for this company. Not a
    # real picker (see module docstring's engine-gap note), just a memory
    # aid for the common re-generate-for-the-same-period case.
    known_period_ids = sorted({r["period_id"] for r in returns if r.get("period_id")})

    flash = request.session.pop("flash", None)
    flash_error = request.session.pop("flash_error", None)

    return _TEMPLATES.TemplateResponse(
        request,
        "tax_returns/list.html",
        {
            "returns": returns,
            "total": len(returns),
            "error": error,
            "flash": flash,
            "flash_error": flash_error,
            "filter_return_type": return_type or "",
            "filter_status": status_filter or "",
            "return_types": _RETURN_TYPES,
            "generatable_types": _GENERATABLE_TYPES,
            "statuses": _STATUSES,
            "known_period_ids": known_period_ids,
            "jurisdiction": _jurisdiction(request),
        },
    )


# ---------------------------------------------------------------------------
# Generate
# ---------------------------------------------------------------------------


@router.post("/tax-returns/generate", response_class=HTMLResponse, response_model=None)
async def tax_returns_generate(request: Request) -> RedirectResponse:
    if not _require_auth(request):
        return RedirectResponse(url="/login", status_code=303)

    form = await request.form()
    return_type = str(form.get("return_type") or "").strip().upper()
    period_id = str(form.get("period_id") or "").strip()

    if not return_type or not period_id:
        request.session["flash_error"] = "Return type and period are both required."
        return RedirectResponse(url="/tax-returns", status_code=303)

    try:
        UUID(period_id)
    except ValueError:
        request.session["flash_error"] = f"'{period_id}' is not a valid period ID."
        return RedirectResponse(url="/tax-returns", status_code=303)

    payload = {
        "jurisdiction": _jurisdiction(request),
        "period_id": period_id,
        "return_type": return_type,
    }

    async with api_client(request) as client:
        resp = await client.post("/api/v1/tax_returns/generate", json=payload)

    if resp.status_code == 401:
        request.session.clear()
        return RedirectResponse(url="/login", status_code=303)

    if resp.status_code == 201:
        body = resp.json()
        request.session["flash"] = (
            f"{return_type} generated for this period — status "
            f"{body.get('status', 'ready')}."
        )
        return RedirectResponse(url=f"/tax-returns/{body['id']}", status_code=303)

    # Honest surfacing: 422 (no box definitions — e.g. TSD, or a period the
    # engine can't find) and any other failure both come from the engine
    # verbatim, never swallowed into a generic "something went wrong".
    detail = f"Generate failed: HTTP {resp.status_code}"
    try:
        body_detail = resp.json().get("detail")
        if isinstance(body_detail, str) and body_detail:
            detail = body_detail
    except Exception:
        pass
    request.session["flash_error"] = detail
    return RedirectResponse(url="/tax-returns", status_code=303)


# ---------------------------------------------------------------------------
# Detail
# ---------------------------------------------------------------------------


@router.get("/tax-returns/{return_id}", response_class=HTMLResponse, response_model=None)
async def tax_returns_detail(
    request: Request, return_id: UUID
) -> HTMLResponse | RedirectResponse:
    if not _require_auth(request):
        return RedirectResponse(url="/login", status_code=303)

    async with api_client(request) as client:
        resp = await client.get(f"/api/v1/tax_returns/{return_id}")
        if resp.status_code == 401:
            request.session.clear()
            return RedirectResponse(url="/login", status_code=303)
        if resp.status_code == 404:
            return HTMLResponse("Tax return not found", status_code=404)
        if not resp.is_success:
            request.session["flash_error"] = f"API error: HTTP {resp.status_code}"
            return RedirectResponse(url="/tax-returns", status_code=303)
        tax_return = resp.json()

        lodgement: dict | None = None
        if tax_return.get("lodgement_record_id"):
            lg_resp = await client.get(f"/api/v1/tax_returns/{return_id}/lodgement")
            if lg_resp.is_success:
                lodgement = lg_resp.json()

    figures = tax_return.get("figures") or {}
    return_type = tax_return.get("return_type") or ""
    jurisdiction = tax_return.get("jurisdiction") or ""

    # Box-vector figures ({box_code: {amount, label, display_order}}) vs
    # TSD's list-shaped figures ({main, lisa1, errors, ...}) — see
    # persist_return / persist_tsd_return in the engine.
    is_box_vector = return_type in ("KMD", "BAS", "IAS") and all(
        isinstance(v, dict) and "amount" in v for v in figures.values()
    )
    boxes: list[dict] = []
    if is_box_vector:
        boxes = sorted(
            (
                {"code": code, **val}
                for code, val in figures.items()
                if isinstance(val, dict)
            ),
            key=lambda b: b.get("display_order", 0),
        )

    tsd_errors = figures.get("errors") if return_type == "TSD" else None
    tsd_main = figures.get("main") if return_type == "TSD" else None
    tsd_lisa1_count = len(figures.get("lisa1") or []) if return_type == "TSD" else 0

    exportable = (jurisdiction, return_type) in _EXPORTABLE_TYPES

    flash = request.session.pop("flash", None)
    flash_error = request.session.pop("flash_error", None)

    return _TEMPLATES.TemplateResponse(
        request,
        "tax_returns/detail.html",
        {
            "tax_return": tax_return,
            "lodgement": lodgement,
            "boxes": boxes,
            "is_box_vector": is_box_vector,
            "tsd_errors": tsd_errors,
            "tsd_main": tsd_main,
            "tsd_lisa1_count": tsd_lisa1_count,
            "exportable": exportable,
            "flash": flash,
            "flash_error": flash_error,
        },
    )


# ---------------------------------------------------------------------------
# Export (download)
# ---------------------------------------------------------------------------


@router.get("/tax-returns/{return_id}/export", response_model=None)
async def tax_returns_export(
    request: Request, return_id: UUID
) -> Response | RedirectResponse:
    if not _require_auth(request):
        return RedirectResponse(url="/login", status_code=303)

    async with api_client(request) as client:
        resp = await client.get(f"/api/v1/tax_returns/{return_id}/export")

    if resp.status_code == 401:
        request.session.clear()
        return RedirectResponse(url="/login", status_code=303)
    if resp.status_code == 404:
        request.session["flash_error"] = "Tax return not found."
        return RedirectResponse(url="/tax-returns", status_code=303)
    if not resp.is_success:
        # 501 (no document builder — e.g. TSD) / 422 (missing period or
        # company ABN/regcode) both surface verbatim rather than a raw
        # error page on what looks like a download link.
        detail = f"Export failed: HTTP {resp.status_code}"
        try:
            body_detail = resp.json().get("detail")
            if isinstance(body_detail, str) and body_detail:
                detail = body_detail
        except Exception:
            pass
        request.session["flash_error"] = detail
        return RedirectResponse(url=f"/tax-returns/{return_id}", status_code=303)

    content_disposition = resp.headers.get(
        "content-disposition", f'attachment; filename="tax_return_{return_id}.xml"'
    )
    return Response(
        content=resp.content,
        media_type=resp.headers.get("content-type", "application/xml"),
        headers={"Content-Disposition": content_disposition},
    )


# ---------------------------------------------------------------------------
# Mark filed
# ---------------------------------------------------------------------------


@router.post(
    "/tax-returns/{return_id}/file", response_class=HTMLResponse, response_model=None
)
async def tax_returns_mark_filed(
    request: Request, return_id: UUID
) -> RedirectResponse:
    if not _require_auth(request):
        return RedirectResponse(url="/login", status_code=303)

    form = await request.form()
    reference = str(form.get("reference") or "").strip()
    payload: dict[str, Any] = {}
    if reference:
        payload["reference"] = reference

    async with api_client(request) as client:
        resp = await client.post(f"/api/v1/tax_returns/{return_id}/file", json=payload)

    if resp.status_code == 401:
        request.session.clear()
        return RedirectResponse(url="/login", status_code=303)
    if resp.status_code == 404:
        request.session["flash_error"] = "Tax return not found."
    elif resp.status_code == 422:
        detail = "This return has already been filed."
        try:
            body_detail = resp.json().get("detail")
            if isinstance(body_detail, str) and body_detail:
                detail = body_detail
        except Exception:
            pass
        request.session["flash_error"] = detail
    elif resp.is_success:
        body = resp.json()
        filed_at = body.get("filed_at") or ""
        request.session["flash"] = f"Marked filed{f' at {filed_at}' if filed_at else ''}."
    else:
        request.session["flash_error"] = f"Mark-filed failed: HTTP {resp.status_code}"

    return RedirectResponse(url=f"/tax-returns/{return_id}", status_code=303)
